Problem1~7 제출합니다
grow-up-study/java-onboarding pull request #3
Opened 2023-03-18 02:03 UTC by dradnats1012

난잡한 코드가 많은데 리뷰부탁드립니다.

2023-03-18 07:08 UTC, Choi-JJunho requested changes
기능 구현을 잘해주셨네요~

이번 미션은 제출 과정 및 진행과정에 익숙해지는 과정이기 때문에 특별히 구현 로직에 관련해서는 코멘트를 남기지는 않았습니다~

# 코드 포맷팅

아래 코멘트에도 작성해뒀지만 코드 포맷팅에 대해 신경써보시면 좋을 것 같아요~

윈도우를 기준으로 IntelliJ 단축키는 다음과 같습니다.

미사용 import 제거 : `Ctrl` + `Alt` + `O`
라인 재정렬 : `Ctrl` + `Alt` + `L`

# PR 제출 시 PR 명

PR 제출 시 다음과 같은 포맷을 지켜주면 좋을 것 같아요.
`[허준기] 온보딩 미션 제출합니다.`

# 코드 컨벤션

다음 미션부터 코드 컨벤션에 대한 내용이 추가 될 예정입니다.
코드 컨벤션과 관련하여 어떤 내용이 있는지 미리 확인해보면 좋을 것 같아요~

- 자바 코드 컨벤션을 지키면서 프로그래밍한다.
  - 참고문서: https://google.github.io/styleguide/javaguide.html 또는 https://myeonguni.tistory.com/1596

2023-03-18 07:08 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem1.java
> +import java.io.OutputStreamWriter;
사용하지 않는 클래스를 import하고 있네요?
Intellij 에서는 미사용 클래스를 정리해주는 기능이 있습니다.

윈도우 기준 : `Ctrl` + `Alt` + `O`

2023-03-18 07:08 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem1.java
> +    public static int compare(int pobiScore, int crongScore){    //포비랑 크롱의 점수 비교
라인 정렬이 안되어있네요~
Intellij 에서는 자동으로 라인을 정렬해주는 기능이 있습니다.

윈도우 기준 : `Ctrl` + `Alt` + `L`

2023-03-18 07:08 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem1.java
> +        return answer;
```suggestion
        return compare(pobiScore, crongScore) ;
```

위와 같이 바로 리턴해주는 방식으로 축약해 줄 수 있겠네요~

2023-03-18 07:08 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem2.java
> +        int c_len = cryptogram.length();                                // 들어오는 문자열의 길이
c_len이라는 네이밍으로는 무슨 역할을 하는 변수인지 알기가 어렵네요~
조금 더 직관적인 네이밍은 없을까요?

2023-03-18 07:08 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem2.java
> +    public static StringBuilder deleteDup(StringBuilder crypArray,int c_len){       // 중복되는 문자 삭제하는 클래스
메소드 명 혹은 변수명을 지을 때 다른 사람이 봤을 때도 알아볼 수 있도록 작성하는게 좋을 것 같아요
이 말에 의하면 메소드명을 축약하는 것은 별로 좋은 방법이 아니겠죠?

주석 없이 읽기좋은 코드를 작성하는 방식에 대해 익숙해져보면 좋을 것 같아요

2023-03-18 07:08 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem3.java
>      }
다른 사람이 봤을 때 해당 메소드가 어떤 과정으로 진행되는 지 알 수 있을까요?

메소드를 분리하여 각각의 조건 혹은 과정이 어떤 역할을 하는지 구분할 수 있을 것 같네요~

2023-03-18 07:08 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem5.java
> +    }
중복되는 로직이 많은 것 같네요~

간결하게 계산할 수 있는 방법이 있을까요?

2023-03-18 07:08 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem6.java
> +}
파일의 가장 마지막줄에 공백(엔터) 가 없으면 경고가 뜨는데 왜 이럴까요?

[참고자료](https://velog.io/@junho5336/No-newline-at-end-of-file)

2023-03-19 09:28 UTC, dradnats1012 commented on src/main/java/onboarding/Problem2.java
> +        int c_len = cryptogram.length();                                // 들어오는 문자열의 길이
cryptogram_length라는 의미였는데 앞으로 변수명 안줄이고 무슨 역할을 하는지 알아볼 수 있도록 하겠습니다

2023-03-19 09:30 UTC, dradnats1012 commented on src/main/java/onboarding/Problem1.java
> +        return answer;
넵 고치겠습니다!!

2023-03-22 02:15 UTC, Choi-JJunho requested changes
잘 수정해주셨네요~
네이밍과 관련된 부분에 대해서 코멘트 남겼으니 반영 부탁드릴게요~

2023-03-22 02:15 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem1.java
> +    public static int plusCalc(int page) {                  //모든 자리수 더하기
plusCalc라는 네이밍으로는 각 자리수를 더한다는 의미가 전달되지 않을 것 같네요!

`plusEachDigit`와 같은 네이밍은 어떨까요?

2023-03-22 02:15 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem2.java
> +        int k = 0;                                                                  // 인덱스 0부터 시작
index라는 네이밍은 어떨가요?

2023-03-22 02:15 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem3.java
> +    public static int clapNum(int number) {
`calculateClapNumber`과 같은 네이밍은 어떨까요?

메소드명은 동사로 시작하면 좋을 것 같아요
[참고자료](https://velog.io/@junho5336/%ED%81%B4%EB%A6%B0%EC%BD%94%EB%93%9C-1)를 한번 읽어보고 네이밍에 대한 고민을 한번 해보시면 좋을 것 같아요

2023-03-22 02:15 UTC, Choi-JJunho commented on src/main/java/onboarding/Problem6.java
> +}
해당 부분에 대한 내용 확인 후 수정부탁드려요~

2023-03-22 02:46 UTC, merged